"""Hand-written realistic notes + the claims a good LLM extractor would emit for them.

Each claim tuple:
  (line, entity_as_written, metric, period, value_text, direction, gt_entity, gt_col, planted, comment)
planted in: correct | hedge | ambiguous | wrong_value | wrong_direction | wrong_entity | wrong_metric | unverifiable
gt_entity is the table row the note's author meant (None if not in the table), gt_col the virtual column meant.
"""

UK = "United Kingdom"
WHH = "WHITE HANGING HEART T-LIGHT HOLDER"
RHH = "RED HANGING HEART T-LIGHT HOLDER"
JHH = "HANGING HEART JAR T-LIGHT HOLDER"

NOTES = {}
CLAIMS = {}

# --------------------------------------------------------------------------- A: small country, LY present
NOTES["A"] = ("small_country_2011-W06", [
    "- Total revenue was £103.7k TW, down 12.1% WoW from £120.3k LW, and up 20.5% YoY.",
    "- The UK generated nearly £90k TW, an 86.5% share, but revenue fell 15.9% WoW (-£17.0k).",
    "- UK revenue was up 20.5% YoY versus £74.5k LY, while UK units dropped 26.1% WoW to 44,149 TW.",
    "- Japan ranked 2nd with £5,735.24 TW, 125.9x its £45.57 LW (+12,485.6% WoW).",
    "- Germany revenue declined 27.0% WoW to £2,840.80 TW and was 31.5% lower YoY; Germany units fell 55.6% WoW.",
    "- France posted the steepest decline, with revenue down 82.3% WoW to £852 TW, a £4,958.50 drop.",
    "- The Netherlands rose 280.4% WoW to £1,256.28 TW, ahead of Spain at £594.11 TW (1.1% share).",
    "- Germany ranked 2nd by revenue TW with 4 orders, down from 9 LW, while Australia revenue was 60.7% below LY.",
])
CLAIMS["A"] = [
    (0, "Total", "revenue", "TW", "£103.7k", "none", "TOTAL", "Revenue_TW", "correct", ""),
    (0, "Total", "revenue", "WoW", "12.1%", "down", "TOTAL", "Revenue_WoW_Pct", "correct", ""),
    (0, "Total", "revenue", "LW", "£120.3k", "none", "TOTAL", "Revenue_LW", "wrong_value", "hallucinated LW total (true 118.0k)"),
    (0, "Total", "revenue", "YoY", "20.5%", "up", "TOTAL", "Revenue_YoY_Pct", "wrong_entity", "UK YoY used for total (true 23.4)"),
    (1, "UK", "revenue", "TW", "£90k", "none", UK, "Revenue_TW", "hedge", "'nearly £90k' for 89,759"),
    (1, "UK", "share", "TW", "86.5%", "none", UK, "Share_Pct", "correct", ""),
    (1, "UK", "revenue", "WoW", "15.9%", "down", UK, "Revenue_WoW_Pct", "correct", ""),
    (1, "UK", "revenue", "WoW", "-£17.0k", "down", UK, "Revenue_WoW_Abs", "correct", ""),
    (2, "UK", "revenue", "YoY", "20.5%", "up", UK, "Revenue_YoY_Pct", "correct", ""),
    (2, "UK", "revenue", "LY", "£74.5k", "none", UK, "Revenue_LY", "correct", ""),
    (2, "UK", "units", "WoW", "26.1%", "down", UK, "Units_WoW_Pct", "wrong_value", "true -29.05"),
    (2, "UK", "units", "TW", "44,149", "none", UK, "Units_TW", "correct", ""),
    (3, "Japan", "rank", "TW", "2nd", "none", "Japan", "Rank", "correct", ""),
    (3, "Japan", "revenue", "TW", "£5,735.24", "none", "Japan", "Revenue_TW", "correct", ""),
    (3, "Japan", "revenue", "WoW", "125.9x", "up", "Japan", "Revenue_WoW_Ratio", "correct", "ratio TW/LW = 125.86"),
    (3, "Japan", "revenue", "LW", "£45.57", "none", "Japan", "Revenue_LW", "correct", ""),
    (3, "Japan", "revenue", "WoW", "+12,485.6%", "up", "Japan", "Revenue_WoW_Pct", "correct", ""),
    (4, "Germany", "revenue", "WoW", "27.0%", "down", "Germany", "Revenue_WoW_Pct", "correct", ""),
    (4, "Germany", "revenue", "TW", "£2,840.80", "none", "Germany", "Revenue_TW", "correct", ""),
    (4, "Germany", "revenue", "YoY", "31.5%", "down", "Germany", "Revenue_YoY_Pct", "correct", ""),
    (4, "Germany", "units", "WoW", "55.6%", "down", "Germany", "Units_WoW_Pct", "wrong_metric", "orders WoW value used for units"),
    (5, "France", "revenue", "WoW", "82.3%", "down", "France", "Revenue_WoW_Pct", "wrong_metric", "YoY value cited as WoW"),
    (5, "France", "revenue", "TW", "£852", "none", "France", "Revenue_TW", "correct", ""),
    (5, "France", "revenue", "WoW", "£4,958.50", "down", "France", "Revenue_WoW_Abs", "wrong_value", "true -4,858.50"),
    (6, "Netherlands", "revenue", "WoW", "280.4%", "up", "Netherlands", "Revenue_WoW_Pct", "correct", ""),
    (6, "Netherlands", "revenue", "TW", "£1,256.28", "none", "Netherlands", "Revenue_TW", "wrong_value", "true 1,156.28"),
    (6, "Spain", "revenue", "TW", "£594.11", "none", "Spain", "Revenue_TW", "correct", ""),
    (6, "Spain", "share", "TW", "1.1%", "none", "Spain", "Share_Pct", "wrong_entity", "Netherlands' share given to Spain"),
    (7, "Germany", "rank", "TW", "2nd", "none", "Germany", "Rank", "wrong_value", "true rank 3"),
    (7, "Germany", "orders", "TW", "4", "none", "Germany", "Orders_TW", "correct", ""),
    (7, "Germany", "orders", "LW", "9", "none", "Germany", "Orders_LW", "correct", ""),
    (7, "Australia", "revenue", "YoY", "60.7%", "down", "Australia", "Revenue_YoY_Pct", "correct", ""),
]

# --------------------------------------------------------------------------- B: small country, EIRE present
NOTES["B"] = ("small_country_2011-W42", [
    "- Total revenue rose 30.3% WoW to £0.25m TW (+£14.8k), and was 10.9% above LY.",
    "- United Kingdom revenue reached £196.5k TW, up 8.1% WoW but down 8.1% YoY.",
    "- UK share of revenue slipped to 77.3% TW from 93.2% LW, down 15.9pp WoW, with orders at 391 vs 393 LW.",
    "- Ireland (EIRE) revenue grew 91.1% WoW to £13.8k TW, a £6.6k increase, and was up 13.0% YoY.",
    "- Germany units rose 112.6% WoW to 6,387 TW, and revenue doubled YoY (+100.8%).",
    "- The Netherlands contributed £29.5k TW from nothing LW, an 11.6% share, ranking 3rd; revenue was up 7,641.5% YoY.",
    "- Sweden generated £5.3k TW on 20,878 units in a single order, while Germany orders rose 16.7% WoW to 17.",
    "- UK units grew 7.0% WoW to 103,879 TW, though UK units were 4.2% lower YoY.",
])
CLAIMS["B"] = [
    (0, "Total", "revenue", "WoW", "30.3%", "up", "TOTAL", "Revenue_WoW_Pct", "correct", ""),
    (0, "Total", "revenue", "TW", "£0.25m", "none", "TOTAL", "Revenue_TW", "correct", ""),
    (0, "Total", "revenue", "WoW", "+£14.8k", "up", "TOTAL", "Revenue_WoW_Abs", "wrong_entity", "UK's WoW change used for total (true +59.1k)"),
    (0, "Total", "revenue", "YoY", "10.9%", "up", "TOTAL", "Revenue_YoY_Pct", "correct", ""),
    (1, "United Kingdom", "revenue", "TW", "£196.5k", "none", UK, "Revenue_TW", "correct", ""),
    (1, "United Kingdom", "revenue", "WoW", "8.1%", "up", UK, "Revenue_WoW_Pct", "correct", ""),
    (1, "United Kingdom", "revenue", "YoY", "8.1%", "down", UK, "Revenue_YoY_Pct", "wrong_value", "true -8.0"),
    (2, "UK", "share", "TW", "77.3%", "none", UK, "Share_Pct", "correct", ""),
    (2, "UK", "share", "LW", "93.2%", "none", UK, "Share_LW", "correct", ""),
    (2, "UK", "share", "WoW", "15.9pp", "down", UK, "Share_WoW_pp", "correct", "share change in points; answerable from table"),
    (2, "UK", "orders", "TW", "391", "none", UK, "Orders_TW", "correct", ""),
    (2, "UK", "orders", "LW", "393", "none", UK, "Orders_LW", "correct", ""),
    (3, "Ireland", "revenue", "WoW", "91.1%", "up", "EIRE", "Revenue_WoW_Pct", "correct", ""),
    (3, "Ireland", "revenue", "TW", "£13.8k", "none", "EIRE", "Revenue_TW", "correct", ""),
    (3, "Ireland", "revenue", "WoW", "£6.6k", "up", "EIRE", "Revenue_WoW_Abs", "correct", ""),
    (3, "Ireland", "revenue", "YoY", "13.0%", "up", "EIRE", "Revenue_YoY_Pct", "wrong_value", "true 30.4"),
    (4, "Germany", "units", "WoW", "112.6%", "up", "Germany", "Units_WoW_Pct", "wrong_entity", "EIRE units WoW"),
    (4, "Germany", "units", "TW", "6,387", "none", "Germany", "Units_TW", "correct", ""),
    (4, "Germany", "revenue", "YoY", "+100.8%", "up", "Germany", "Revenue_YoY_Pct", "correct", ""),
    (5, "Netherlands", "revenue", "TW", "£29.5k", "none", "Netherlands", "Revenue_TW", "correct", ""),
    (5, "Netherlands", "share", "TW", "11.6%", "none", "Netherlands", "Share_Pct", "correct", ""),
    (5, "Netherlands", "rank", "TW", "3rd", "none", "Netherlands", "Rank", "wrong_value", "true rank 2"),
    (5, "Netherlands", "revenue", "YoY", "7,641.5%", "up", "Netherlands", "Revenue_YoY_Pct", "correct", ""),
    (6, "Sweden", "revenue", "TW", "£5.3k", "none", "Sweden", "Revenue_TW", "correct", ""),
    (6, "Sweden", "units", "TW", "20,878", "none", "Sweden", "Units_TW", "wrong_entity", "Netherlands units"),
    (6, "Germany", "orders", "WoW", "16.7%", "up", "Germany", "Orders_WoW_Pct", "wrong_entity", "EIRE orders WoW (true +54.5)"),
    (6, "Germany", "orders", "TW", "17", "none", "Germany", "Orders_TW", "correct", ""),
    (7, "UK", "units", "WoW", "7.0%", "up", UK, "Units_WoW_Pct", "wrong_value", "true +7.28"),
    (7, "UK", "units", "TW", "103,879", "none", UK, "Units_TW", "correct", ""),
    (7, "UK", "units", "YoY", "4.2%", "down", UK, "Units_YoY_Pct", "unverifiable", "no Units_LY column"),
]

# --------------------------------------------------------------------------- C: large product table, similar names
NOTES["C"] = ("large_product_2011-W06", [
    "- Total revenue across the 139 products was £58.8k TW, up 48.9% WoW (+£19.3k), with total units up 48.9% WoW.",
    "- Vintage Union Jack memoboard led with £6.5k TW, an 11.0% share, up from just £9.95 LW.",
    "- White Hanging Heart holder revenue slipped 13.9% WoW to £1,393 TW on 588 units, and was also down 13.9% YoY.",
    "- Jumbo Bag Red Retrospot fell 68.2% WoW to £569 TW, a £1.2k drop, while Lunch bag red retrospot declined 68.2% WoW to £434 TW.",
    "- Red Hanging Heart T-light holder revenue fell 13.9% WoW to £235 TW, while the Hanging Heart jar T-light holder rose 9.0% WoW to £220 TW.",
    "- Regency cakestand revenue was broadly flat, down 1.6% WoW at £1.86k TW, on 150 units TW.",
    "- Party bunting revenue fell 17.1% WoW to £1,255 TW but was up 389.7% YoY.",
    "- Heart of Wicker small dropped 44.0% WoW while Chilli lights grew 37.9% WoW to £985 TW.",
])
CLAIMS["C"] = [
    (0, "Total", "revenue", "TW", "£58.8k", "none", "TOTAL", "Revenue_TW", "correct", ""),
    (0, "Total", "revenue", "WoW", "48.9%", "up", "TOTAL", "Revenue_WoW_Pct", "correct", ""),
    (0, "Total", "revenue", "WoW", "+£19.3k", "up", "TOTAL", "Revenue_WoW_Abs", "correct", ""),
    (0, "Total", "units", "WoW", "48.9%", "up", "TOTAL", "Units_WoW_Pct", "wrong_metric", "revenue WoW used for units (true +55.9)"),
    (1, "Vintage Union Jack memoboard", "revenue", "TW", "£6.5k", "none", "VINTAGE UNION JACK MEMOBOARD", "Revenue_TW", "correct", ""),
    (1, "Vintage Union Jack memoboard", "share", "TW", "11.0%", "none", "VINTAGE UNION JACK MEMOBOARD", "Share_Pct", "correct", ""),
    (1, "Vintage Union Jack memoboard", "revenue", "LW", "£9.95", "none", "VINTAGE UNION JACK MEMOBOARD", "Revenue_LW", "correct", ""),
    (2, "White Hanging Heart holder", "revenue", "WoW", "13.9%", "down", WHH, "Revenue_WoW_Pct", "correct", ""),
    (2, "White Hanging Heart holder", "revenue", "TW", "£1,393", "none", WHH, "Revenue_TW", "correct", ""),
    (2, "White Hanging Heart holder", "units", "TW", "588", "none", WHH, "Units_TW", "wrong_metric", "LW units cited as TW (true 517)"),
    (2, "White Hanging Heart holder", "revenue", "YoY", "13.9%", "down", WHH, "Revenue_YoY_Pct", "correct", ""),
    (3, "Jumbo Bag Red Retrospot", "revenue", "WoW", "68.2%", "down", "JUMBO BAG RED RETROSPOT", "Revenue_WoW_Pct", "correct", ""),
    (3, "Jumbo Bag Red Retrospot", "revenue", "TW", "£569", "none", "JUMBO BAG RED RETROSPOT", "Revenue_TW", "correct", ""),
    (3, "Jumbo Bag Red Retrospot", "revenue", "WoW", "£1.2k", "down", "JUMBO BAG RED RETROSPOT", "Revenue_WoW_Abs", "correct", ""),
    (3, "Lunch bag red retrospot", "revenue", "WoW", "68.2%", "down", "LUNCH BAG RED RETROSPOT", "Revenue_WoW_Pct", "wrong_entity", "Jumbo bag's WoW copied (true -41.0)"),
    (3, "Lunch bag red retrospot", "revenue", "TW", "£434", "none", "LUNCH BAG RED RETROSPOT", "Revenue_TW", "correct", ""),
    (4, "Red Hanging Heart T-light holder", "revenue", "WoW", "13.9%", "down", RHH, "Revenue_WoW_Pct", "wrong_entity", "WHITE's WoW (true -38.3)"),
    (4, "Red Hanging Heart T-light holder", "revenue", "TW", "£235", "none", RHH, "Revenue_TW", "correct", ""),
    (4, "Hanging Heart jar T-light holder", "revenue", "WoW", "9.0%", "up", JHH, "Revenue_WoW_Pct", "correct", ""),
    (4, "Hanging Heart jar T-light holder", "revenue", "TW", "£220", "none", JHH, "Revenue_TW", "correct", ""),
    (5, "Regency cakestand", "revenue", "WoW", "1.6%", "down", "REGENCY CAKESTAND 3 TIER", "Revenue_WoW_Pct", "correct", ""),
    (5, "Regency cakestand", "revenue", "TW", "£1.86k", "none", "REGENCY CAKESTAND 3 TIER", "Revenue_TW", "correct", ""),
    (5, "Regency cakestand", "units", "TW", "150", "none", "REGENCY CAKESTAND 3 TIER", "Units_TW", "wrong_metric", "LW units cited as TW (true 139)"),
    (6, "Party bunting", "revenue", "WoW", "17.1%", "down", "PARTY BUNTING", "Revenue_WoW_Pct", "wrong_direction", "true +17.1"),
    (6, "Party bunting", "revenue", "TW", "£1,255", "none", "PARTY BUNTING", "Revenue_TW", "correct", ""),
    (6, "Party bunting", "revenue", "YoY", "389.7%", "up", "PARTY BUNTING", "Revenue_YoY_Pct", "correct", ""),
    (7, "Heart of Wicker small", "revenue", "WoW", "44.0%", "down", "HEART OF WICKER SMALL", "Revenue_WoW_Pct", "wrong_metric", "units WoW (-44.02) cited as revenue (true -43.1)"),
    (7, "Chilli lights", "revenue", "WoW", "37.9%", "up", "CHILLI LIGHTS", "Revenue_WoW_Pct", "wrong_value", "digits transposed (true 73.9)"),
    (7, "Chilli lights", "revenue", "TW", "£985", "none", "CHILLI LIGHTS", "Revenue_TW", "correct", ""),
]

# --------------------------------------------------------------------------- D: same large table, shortened / ambiguous names
NOTES["D"] = ("large_product_2011-W06", [
    "- Cream heart card holder ranked 2nd with £2.4k TW, up more than 900% WoW, on 1,015 units TW.",
    "- Grow a flytrap tin sold 2,451 units TW, up from 48 LW, for £2,391.75 TW.",
    "- The top 10 products generated £20.0k TW, 34.0% of total revenue.",
    "- Retrospot cake cases units fell 37.8% WoW to 347 TW, and Red Retrospot napkins revenue rose 91.1% WoW.",
    "- Hanging heart T-light holder revenue fell 38.3% WoW to £234.89 TW.",
    "- Polkadot cutlery set revenue jumped 283.8% WoW to £207 TW.",
    "- Regency teacup and saucer revenue fell 71.2% WoW to £182 TW.",
    "- Retrospot doormat revenue halved, down 51.1% WoW to £211 TW, as orders fell to 7 TW from 17 LW.",
])
CLAIMS["D"] = [
    (0, "Cream heart card holder", "rank", "TW", "2nd", "none", "CREAM HEART CARD HOLDER", "Rank", "correct", ""),
    (0, "Cream heart card holder", "revenue", "TW", "£2.4k", "none", "CREAM HEART CARD HOLDER", "Revenue_TW", "correct", ""),
    (0, "Cream heart card holder", "revenue", "WoW", "900%", "up", "CREAM HEART CARD HOLDER", "Revenue_WoW_Pct", "hedge", "'more than 900%' for 910.8"),
    (0, "Cream heart card holder", "units", "TW", "1,015", "none", "CREAM HEART CARD HOLDER", "Units_TW", "wrong_entity", "memoboard's units (true 1,027)"),
    (1, "Grow a flytrap tin", "units", "TW", "2,451", "none", "GROW A FLYTRAP OR SUNFLOWER IN TIN", "Units_TW", "correct", ""),
    (1, "Grow a flytrap tin", "units", "LW", "48", "none", "GROW A FLYTRAP OR SUNFLOWER IN TIN", "Units_LW", "correct", ""),
    (1, "Grow a flytrap tin", "revenue", "TW", "£2,391.75", "none", "GROW A FLYTRAP OR SUNFLOWER IN TIN", "Revenue_TW", "wrong_value", "true 2,319.75"),
    (2, "Top 10 products", "revenue", "TW", "£20.0k", "none", None, "Top10_Revenue", "unverifiable", "group claim, no row (value is actually right)"),
    (2, "Top 10 products", "share", "TW", "34.0%", "none", None, "Top10_Share", "unverifiable", "group claim, no row (value is actually right)"),
    (3, "Retrospot cake cases", "units", "WoW", "37.8%", "down", "PACK OF 72 RETROSPOT CAKE CASES", "Units_WoW_Pct", "correct", ""),
    (3, "Retrospot cake cases", "units", "TW", "347", "none", "PACK OF 72 RETROSPOT CAKE CASES", "Units_TW", "correct", ""),
    (3, "Red Retrospot napkins", "revenue", "WoW", "91.1%", "up", "SET/20 RED RETROSPOT PAPER NAPKINS", "Revenue_WoW_Pct", "wrong_value", "true +19.1"),
    (4, "Hanging heart T-light holder", "revenue", "WoW", "38.3%", "down", RHH, "Revenue_WoW_Pct", "ambiguous", "numbers are the RED holder's"),
    (4, "Hanging heart T-light holder", "revenue", "TW", "£234.89", "none", RHH, "Revenue_TW", "ambiguous", "numbers are the RED holder's"),
    (5, "Polkadot cutlery set", "revenue", "WoW", "283.8%", "up", "GREEN 3 PIECE POLKADOT CUTLERY SET", "Revenue_WoW_Pct", "ambiguous", "numbers are the GREEN set's"),
    (5, "Polkadot cutlery set", "revenue", "TW", "£207", "none", "GREEN 3 PIECE POLKADOT CUTLERY SET", "Revenue_TW", "ambiguous", "numbers are the GREEN set's"),
    (6, "Regency teacup and saucer", "revenue", "WoW", "71.2%", "down", "ROSES REGENCY TEACUP AND SAUCER", "Revenue_WoW_Pct", "ambiguous", "numbers are the ROSES one's"),
    (6, "Regency teacup and saucer", "revenue", "TW", "£182", "none", "ROSES REGENCY TEACUP AND SAUCER", "Revenue_TW", "ambiguous", "numbers are the ROSES one's"),
    (7, "Retrospot doormat", "revenue", "WoW", "51.1%", "down", "DOORMAT RED RETROSPOT", "Revenue_WoW_Pct", "correct", ""),
    (7, "Retrospot doormat", "revenue", "TW", "£211", "none", "DOORMAT RED RETROSPOT", "Revenue_TW", "correct", ""),
    (7, "Retrospot doormat", "orders", "TW", "7", "none", "DOORMAT RED RETROSPOT", "Orders_TW", "correct", ""),
    (7, "Retrospot doormat", "orders", "LW", "17", "none", "DOORMAT RED RETROSPOT", "Orders_LW", "wrong_value", "true 16"),
]

# --------------------------------------------------------------------------- E: medium product table, many hot water bottles
NOTES["E"] = ("medium_product_2010-W50", [
    "- Overall revenue was £0.61m TW, down 6.3% WoW (-£4.1k), but up 93.1% YoY.",
    "- Regency Cakestand 3 Tier stayed 1st at £5.9k TW (7.0% share), although revenue fell 45.7% WoW from £10.9k LW.",
    "- White Hanging Heart T-Light Holder revenue rose 20.6% WoW to £4,251.25 TW but was down 49.4% YoY from £8.4k LY.",
    "- Chocolate hot water bottle revenue rose 16.1% WoW to £2.1k TW, while Scottie dog hot water bottle was down 42.5% WoW.",
    "- White skull hot water bottle dropped 58.7% WoW, a £1,976 decline, and Tea and Sympathy hot water bottle orders fell from 48 LW to 4 TW.",
    "- Grey heart hot water bottle revenue rose 34.8% WoW to £1,113 TW, and Chick grey hot water bottle jumped 221.4% WoW.",
    "- Heart hot water bottle revenue grew 16.8% WoW to £1,299 TW.",
    "- Knitted Union Flag hot water bottle units fell 40.1% WoW to 286 TW, while Paper chain kit revenue fell 46.9% WoW.",
])
RC = "REGENCY CAKESTAND 3 TIER"
CLAIMS["E"] = [
    (0, "overall", "revenue", "TW", "£0.61m", "none", "TOTAL", "Revenue_TW", "wrong_value", "10x scale error (true £60.7k)"),
    (0, "overall", "revenue", "WoW", "6.3%", "down", "TOTAL", "Revenue_WoW_Pct", "correct", ""),
    (0, "overall", "revenue", "WoW", "-£4.1k", "down", "TOTAL", "Revenue_WoW_Abs", "correct", ""),
    (0, "overall", "revenue", "YoY", "93.1%", "up", "TOTAL", "Revenue_YoY_Pct", "correct", ""),
    (1, "Regency Cakestand 3 Tier", "rank", "TW", "1st", "none", RC, "Rank", "correct", ""),
    (1, "Regency Cakestand 3 Tier", "revenue", "TW", "£5.9k", "none", RC, "Revenue_TW", "correct", ""),
    (1, "Regency Cakestand 3 Tier", "share", "TW", "7.0%", "none", RC, "Share_Pct", "wrong_entity", "White Hanging Heart's share (true 9.7)"),
    (1, "Regency Cakestand 3 Tier", "revenue", "WoW", "45.7%", "down", RC, "Revenue_WoW_Pct", "correct", ""),
    (1, "Regency Cakestand 3 Tier", "revenue", "LW", "£10.9k", "none", RC, "Revenue_LW", "correct", ""),
    (2, "White Hanging Heart T-Light Holder", "revenue", "WoW", "20.6%", "up", WHH, "Revenue_WoW_Pct", "wrong_entity", "adjacent row (Rotating Silver Angels) 20.6; true 20.1"),
    (2, "White Hanging Heart T-Light Holder", "revenue", "TW", "£4,251.25", "none", WHH, "Revenue_TW", "correct", ""),
    (2, "White Hanging Heart T-Light Holder", "revenue", "YoY", "49.4%", "down", WHH, "Revenue_YoY_Pct", "correct", ""),
    (2, "White Hanging Heart T-Light Holder", "revenue", "LY", "£8.4k", "none", WHH, "Revenue_LY", "correct", ""),
    (3, "Chocolate hot water bottle", "revenue", "WoW", "16.1%", "up", "CHOCOLATE HOT WATER BOTTLE", "Revenue_WoW_Pct", "wrong_direction", "true -16.1"),
    (3, "Chocolate hot water bottle", "revenue", "TW", "£2.1k", "none", "CHOCOLATE HOT WATER BOTTLE", "Revenue_TW", "correct", ""),
    (3, "Scottie dog hot water bottle", "revenue", "WoW", "42.5%", "down", "SCOTTIE DOG HOT WATER BOTTLE", "Revenue_WoW_Pct", "wrong_metric", "YoY value cited as WoW (true -1.6)"),
    (4, "White skull hot water bottle", "revenue", "WoW", "58.7%", "down", "WHITE SKULL HOT WATER BOTTLE", "Revenue_WoW_Pct", "correct", ""),
    (4, "White skull hot water bottle", "revenue", "WoW", "£1,976", "down", "WHITE SKULL HOT WATER BOTTLE", "Revenue_WoW_Abs", "correct", ""),
    (4, "Tea and Sympathy hot water bottle", "orders", "LW", "48", "none", "HOT WATER BOTTLE TEA AND SYMPATHY", "Orders_LW", "correct", ""),
    (4, "Tea and Sympathy hot water bottle", "orders", "TW", "4", "none", "HOT WATER BOTTLE TEA AND SYMPATHY", "Orders_TW", "correct", ""),
    (5, "Grey heart hot water bottle", "revenue", "WoW", "34.8%", "up", "GREY HEART HOT WATER BOTTLE", "Revenue_WoW_Pct", "correct", ""),
    (5, "Grey heart hot water bottle", "revenue", "TW", "£1,113", "none", "GREY HEART HOT WATER BOTTLE", "Revenue_TW", "wrong_value", "true 1,013.21"),
    (5, "Chick grey hot water bottle", "revenue", "WoW", "221.4%", "up", "CHICK GREY HOT WATER BOTTLE", "Revenue_WoW_Pct", "wrong_metric", "units WoW (221.43) cited as revenue (true 164.0)"),
    (6, "Heart hot water bottle", "revenue", "WoW", "16.8%", "up", "RETROSPOT HEART HOT WATER BOTTLE", "Revenue_WoW_Pct", "ambiguous", "numbers are the RETROSPOT HEART one's"),
    (6, "Heart hot water bottle", "revenue", "TW", "£1,299", "none", "RETROSPOT HEART HOT WATER BOTTLE", "Revenue_TW", "ambiguous", "numbers are the RETROSPOT HEART one's"),
    (7, "Knitted Union Flag hot water bottle", "units", "WoW", "40.1%", "down", "KNITTED UNION FLAG HOT WATER BOTTLE", "Units_WoW_Pct", "wrong_metric", "revenue WoW cited as units (true -27.8)"),
    (7, "Knitted Union Flag hot water bottle", "units", "TW", "286", "none", "KNITTED UNION FLAG HOT WATER BOTTLE", "Units_TW", "correct", ""),
    (7, "Paper chain kit", "revenue", "WoW", "46.9%", "down", "PAPER CHAIN KIT 50'S CHRISTMAS", "Revenue_WoW_Pct", "ambiguous", "numbers are the 50'S CHRISTMAS kit's"),
]

# --------------------------------------------------------------------------- F: large product table, hanging hearts + retrospot
NOTES["F"] = ("large_product_2011-W08", [
    "- Total revenue grew 32.5% WoW to £67.4k TW, with units up 57.9% WoW to 31,218.",
    "- Empire design rosette led at £3.3k TW (4.9% share) after just £12.50 LW.",
    "- Jumbo bag red retrospot ranked 3rd with £1,482 TW, down 14.5% WoW, and Lunch bag red retrospot rose 24.4% WoW to £630 TW.",
    "- White hanging heart T-light holder revenue was up 11.9% WoW to £1,001 TW but down 55.2% YoY; Red hanging heart T-light holder surged 545.1% WoW.",
    "- Hanging heart jar T-light holder units rose 249.3% WoW to 475 TW, while Pink hanging heart candleholder revenue rose 199.5% WoW.",
    "- Retrospot windmill revenue soared 1,957.1% WoW to £475 TW, and Retrospot tea towels rose 1,840.0% YoY.",
    "- Red Retrospot cutlery set revenue fell 60.2% WoW to £370 TW, a £590 drop, on 245 units.",
    "- Recycling bag retrospot revenue rose 89.6% WoW but was 40.9% lower YoY and units were 71.5% lower YoY; orders totalled 1,940 TW, up 22.5% WoW.",
])
JB, LB = "JUMBO BAG RED RETROSPOT", "LUNCH BAG RED RETROSPOT"
CUT, REC = "RED 3 PIECE RETROSPOT CUTLERY SET", "RECYCLING BAG RETROSPOT"
CLAIMS["F"] = [
    (0, "Total", "revenue", "WoW", "32.5%", "up", "TOTAL", "Revenue_WoW_Pct", "correct", ""),
    (0, "Total", "revenue", "TW", "£67.4k", "none", "TOTAL", "Revenue_TW", "correct", ""),
    (0, "Total", "units", "WoW", "57.9%", "up", "TOTAL", "Units_WoW_Pct", "correct", ""),
    (0, "Total", "units", "TW", "31,218", "none", "TOTAL", "Units_TW", "correct", ""),
    (1, "Empire design rosette", "revenue", "TW", "£3.3k", "none", "EMPIRE DESIGN ROSETTE", "Revenue_TW", "correct", ""),
    (1, "Empire design rosette", "share", "TW", "4.9%", "none", "EMPIRE DESIGN ROSETTE", "Share_Pct", "correct", ""),
    (1, "Empire design rosette", "revenue", "LW", "£12.50", "none", "EMPIRE DESIGN ROSETTE", "Revenue_LW", "correct", ""),
    (2, "Jumbo bag red retrospot", "rank", "TW", "3rd", "none", JB, "Rank", "wrong_value", "true rank 4"),
    (2, "Jumbo bag red retrospot", "revenue", "TW", "£1,482", "none", JB, "Revenue_TW", "correct", ""),
    (2, "Jumbo bag red retrospot", "revenue", "WoW", "14.5%", "down", JB, "Revenue_WoW_Pct", "correct", ""),
    (2, "Lunch bag red retrospot", "revenue", "WoW", "24.4%", "up", LB, "Revenue_WoW_Pct", "correct", ""),
    (2, "Lunch bag red retrospot", "revenue", "TW", "£630", "none", LB, "Revenue_TW", "correct", ""),
    (3, "White hanging heart T-light holder", "revenue", "WoW", "11.9%", "up", WHH, "Revenue_WoW_Pct", "correct", ""),
    (3, "White hanging heart T-light holder", "revenue", "TW", "£1,001", "none", WHH, "Revenue_TW", "wrong_metric", "LW revenue cited as TW (true 1,119.63)"),
    (3, "White hanging heart T-light holder", "revenue", "YoY", "55.2%", "down", WHH, "Revenue_YoY_Pct", "correct", ""),
    (3, "Red hanging heart T-light holder", "revenue", "WoW", "545.1%", "up", RHH, "Revenue_WoW_Pct", "correct", ""),
    (4, "Hanging heart jar T-light holder", "units", "WoW", "249.3%", "up", JHH, "Units_WoW_Pct", "correct", ""),
    (4, "Hanging heart jar T-light holder", "units", "TW", "475", "none", JHH, "Units_TW", "correct", ""),
    (4, "Pink hanging heart candleholder", "revenue", "WoW", "199.5%", "up", "CANDLEHOLDER PINK HANGING HEART", "Revenue_WoW_Pct", "wrong_entity", "jar holder's WoW (true 51.9)"),
    (5, "Retrospot windmill", "revenue", "WoW", "1,957.1%", "up", "LARGE RED RETROSPOT WINDMILL", "Revenue_WoW_Pct", "correct", ""),
    (5, "Retrospot windmill", "revenue", "TW", "£475", "none", "LARGE RED RETROSPOT WINDMILL", "Revenue_TW", "correct", ""),
    (5, "Retrospot tea towels", "revenue", "YoY", "1,840.0%", "up", "SET/2 RED RETROSPOT TEA TOWELS", "Revenue_YoY_Pct", "wrong_metric", "WoW % labelled YoY; YoY undefined (LY=0)"),
    (6, "Red Retrospot cutlery set", "revenue", "WoW", "60.2%", "down", CUT, "Revenue_WoW_Pct", "correct", ""),
    (6, "Red Retrospot cutlery set", "revenue", "TW", "£370", "none", CUT, "Revenue_TW", "correct", ""),
    (6, "Red Retrospot cutlery set", "revenue", "WoW", "£590", "down", CUT, "Revenue_WoW_Abs", "wrong_value", "true -559.67"),
    (6, "Red Retrospot cutlery set", "units", "TW", "245", "none", CUT, "Units_TW", "wrong_metric", "LW units cited as TW (true 96)"),
    (7, "Recycling bag retrospot", "revenue", "WoW", "89.6%", "up", REC, "Revenue_WoW_Pct", "correct", ""),
    (7, "Recycling bag retrospot", "revenue", "YoY", "40.9%", "down", REC, "Revenue_YoY_Pct", "correct", ""),
    (7, "Recycling bag retrospot", "units", "YoY", "71.5%", "down", REC, "Units_YoY_Pct", "unverifiable", "no Units_LY column"),
    (7, "Total", "orders", "TW", "1,940", "none", "TOTAL", "Orders_TW", "correct", ""),
    (7, "Total", "orders", "WoW", "22.5%", "up", "TOTAL", "Orders_WoW_Pct", "correct", ""),
]

# --------------------------------------------------------------------------- G: small country, 10 rows, alias + absent entity
NOTES["G"] = ("small_country_2010-W50", [
    "- Total revenue fell 27.7% WoW to £208.7k TW and was 9.9% below LY, a £23.0k YoY decline.",
    "- The UK fell 30.3% WoW to £193.4k TW, a 92.6% share, and was 13.0% higher YoY.",
    "- Germany revenue rose 16.2% WoW to £4.5k TW, up 16.2% YoY, and ranked 2nd.",
    "- Ireland revenue fell 24.9% WoW to £3,184.10 TW, and was down 26.5% YoY.",
    "- Sweden ranked 3rd with £3.8k TW, up 1,244.0% YoY, from 3,594 units.",
    "- Spain revenue jumped 420.3% WoW to £909 TW, while France collapsed 73.3% WoW to £515 TW (-£3.5k).",
    "- USA revenue was £1,121 TW, and Finland revenue was up 39.2% YoY to £653 TW.",
    "- Belgium orders were 2 TW, Australia orders were 1 TW, and Cyprus had a 0.3% share with 917 units.",
])
CLAIMS["G"] = [
    (0, "Total", "revenue", "WoW", "27.7%", "down", "TOTAL", "Revenue_WoW_Pct", "correct", ""),
    (0, "Total", "revenue", "TW", "£208.7k", "none", "TOTAL", "Revenue_TW", "correct", ""),
    (0, "Total", "revenue", "YoY", "9.9%", "down", "TOTAL", "Revenue_YoY_Pct", "correct", ""),
    (0, "Total", "revenue", "YoY", "£23.0k", "down", "TOTAL", "Revenue_YoY_Abs", "correct", ""),
    (1, "UK", "revenue", "WoW", "30.3%", "down", UK, "Revenue_WoW_Pct", "correct", ""),
    (1, "UK", "revenue", "TW", "£193.4k", "none", UK, "Revenue_TW", "correct", ""),
    (1, "UK", "share", "TW", "92.6%", "none", UK, "Share_Pct", "correct", ""),
    (1, "UK", "revenue", "YoY", "13.0%", "up", UK, "Revenue_YoY_Pct", "wrong_direction", "true -13.0"),
    (2, "Germany", "revenue", "WoW", "16.2%", "up", "Germany", "Revenue_WoW_Pct", "correct", ""),
    (2, "Germany", "revenue", "TW", "£4.5k", "none", "Germany", "Revenue_TW", "correct", ""),
    (2, "Germany", "revenue", "YoY", "16.2%", "up", "Germany", "Revenue_YoY_Pct", "wrong_metric", "WoW value cited as YoY (true 42.6)"),
    (2, "Germany", "rank", "TW", "2nd", "none", "Germany", "Rank", "correct", ""),
    (3, "Ireland", "revenue", "WoW", "24.9%", "down", "EIRE", "Revenue_WoW_Pct", "correct", ""),
    (3, "Ireland", "revenue", "TW", "£3,184.10", "none", "EIRE", "Revenue_TW", "wrong_metric", "LW revenue cited as TW (true 2,392.28)"),
    (3, "Ireland", "revenue", "YoY", "26.5%", "down", "EIRE", "Revenue_YoY_Pct", "correct", ""),
    (4, "Sweden", "rank", "TW", "3rd", "none", "Sweden", "Rank", "correct", ""),
    (4, "Sweden", "revenue", "TW", "£3.8k", "none", "Sweden", "Revenue_TW", "correct", ""),
    (4, "Sweden", "revenue", "YoY", "1,244.0%", "up", "Sweden", "Revenue_YoY_Pct", "correct", ""),
    (4, "Sweden", "units", "TW", "3,594", "none", "Sweden", "Units_TW", "wrong_value", "digits transposed (true 3,954)"),
    (5, "Spain", "revenue", "WoW", "420.3%", "up", "Spain", "Revenue_WoW_Pct", "correct", ""),
    (5, "Spain", "revenue", "TW", "£909", "none", "Spain", "Revenue_TW", "correct", ""),
    (5, "France", "revenue", "WoW", "73.3%", "down", "France", "Revenue_WoW_Pct", "wrong_metric", "YoY value cited as WoW (true -87.3)"),
    (5, "France", "revenue", "TW", "£515", "none", "France", "Revenue_TW", "correct", ""),
    (5, "France", "revenue", "WoW", "-£3.5k", "down", "France", "Revenue_WoW_Abs", "correct", ""),
    (6, "USA", "revenue", "TW", "£1,121", "none", None, "Revenue_TW", "unverifiable", "USA not in table"),
    (6, "Finland", "revenue", "YoY", "39.2%", "up", "Finland", "Revenue_YoY_Pct", "correct", ""),
    (6, "Finland", "revenue", "TW", "£653", "none", "Finland", "Revenue_TW", "correct", ""),
    (7, "Belgium", "orders", "TW", "2", "none", "Belgium", "Orders_TW", "correct", ""),
    (7, "Australia", "orders", "TW", "1", "none", "Australia", "Orders_TW", "correct", ""),
    (7, "Cyprus", "share", "TW", "0.3%", "none", "Cyprus", "Share_Pct", "wrong_value", "true 0.8 (0.3 is Finland/Belgium's)"),
    (7, "Cyprus", "units", "TW", "917", "none", "Cyprus", "Units_TW", "correct", ""),
]

# --------------------------------------------------------------------------- extractor-variance probe
# Same lines, but an alternative emission a reasonable extractor could produce. (note, line, entity, metric,
# period, value_text, direction, gt_entity, gt_col, planted, comment)
PROBES = [
    ("A", 4, "Germany", "revenue", "TW", "£2,840.80", "down", "Germany", "Revenue_TW", "correct", "level after 'declined ... to' tagged down"),
    ("C", 3, "Jumbo Bag Red Retrospot", "revenue", "TW", "£569", "down", "JUMBO BAG RED RETROSPOT", "Revenue_TW", "correct", "level after 'fell ... to' tagged down"),
    ("E", 4, "Tea and Sympathy hot water bottle", "orders", "TW", "4", "down", "HOT WATER BOTTLE TEA AND SYMPATHY", "Orders_TW", "correct", "level after 'fell from 48 to' tagged down"),
    ("D", 7, "Retrospot doormat", "revenue", "TW", "£211", "down", "DOORMAT RED RETROSPOT", "Revenue_TW", "correct", "level after 'down 51.1% WoW to' tagged down"),
    ("B", 3, "Ireland (EIRE)", "revenue", "TW", "£13.8k", "none", "EIRE", "Revenue_TW", "correct", "entity copied with parenthetical"),
    ("B", 3, "Irish", "revenue", "TW", "£13.8k", "none", "EIRE", "Revenue_TW", "correct", "adjective form"),
    ("G", 1, "The UK", "revenue", "TW", "£193.4k", "none", UK, "Revenue_TW", "correct", "article kept"),
    ("G", 1, "British", "revenue", "TW", "£193.4k", "none", UK, "Revenue_TW", "correct", "adjective form"),
    ("D", 2, "Total", "revenue", "TW", "£20.0k", "none", None, "Top10_Revenue", "unverifiable", "extractor collapses 'top 10 products' to TOTAL"),
    ("A", 1, "UK", "revenue", "WoW", "−15.9%", "down", UK, "Revenue_WoW_Pct", "correct", "unicode minus"),
    ("A", 1, "UK", "revenue", "WoW", "15.9 percent", "down", UK, "Revenue_WoW_Pct", "correct", "spelled percent"),
    ("A", 2, "UK", "units", "TW", "44.1k", "none", UK, "Units_TW", "correct", "units in k"),
    ("A", 2, "UK", "units", "WoW", "18,076", "down", UK, "Units_WoW_Abs", "correct", "absolute units change"),
    ("A", 2, "UK", "units", "WoW", "18,076 units", "down", UK, "Units_WoW_Abs", "correct", "absolute units change with noun"),
    ("C", 1, "Vintage Union Jack memoboard", "revenue", "TW", "£6.5k", "none", "VINTAGE UNION JACK MEMOBOARD", "Revenue_TW", "correct", "baseline"),
    ("C", 0, "All products", "revenue", "TW", "£58.8k", "none", "TOTAL", "Revenue_TW", "correct", "TOTAL word variant"),
    ("C", 0, "The business", "revenue", "TW", "£58.8k", "none", "TOTAL", "Revenue_TW", "correct", "TOTAL word variant with article"),
    ("C", 0, "Across all 139 products", "revenue", "TW", "£58.8k", "none", "TOTAL", "Revenue_TW", "correct", "TOTAL phrase"),
    ("B", 2, "UK", "share", "WoW", "-15.9pp", "down", UK, "Share_WoW_pp", "correct", "share change, signed"),
    ("A", 0, "Total", "revenue", "WoW", "-12.1%", "up", "TOTAL", "Revenue_WoW_Pct", "correct", "value_text sign contradicts extractor direction (extractor slip); value is right"),
    ("A", 3, "Japan", "revenue", "WoW", "12,486%", "up", "Japan", "Revenue_WoW_Pct", "correct", "rounded to integer"),
    ("A", 3, "Japan", "revenue", "WoW", "over 12,000%", "up", "Japan", "Revenue_WoW_Pct", "hedge", "extractor keeps hedge word"),
]
